services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      LUCEBOT_CONFIG_PATH: /app/config/config.json
    volumes:
      - type: bind
        source: ./config
        target: /app/config
      - ./data:/app/data
